### PR TITLE
typos & some trivial fixes

### PR DESCRIPTION
**Pull request by maowug**
Change:
- fix typos in  *Binding.scala
- remove unnecessary finals in final classes?

I'm new to Binding.scala, just completed the doc. Is there any way to do conditional bindind in `bind` or `@dom`, when we want to ignore some `Var` updating?

### CODE REVIEW

**Comment by Atry** [comment]
Thank you!

**Comment by Atry** [comment]
Hi @maowug , would you like to port this patch to 10.0.x as well?

**Comment by Atry** [comment]
BTW: I did not understand what does "conditional binding" mean. Could you give an example please?

**Comment by maowug** [comment]
@Atry Thank you for the 10.0.x patch. By `conditional bindind` I mean `conditional updating` kinda like what `shouldComponentUpdate` does. Never mind, I'll open an issue if there is a real use case.   👍

**Comment by Atry** [comment]
ReactJS need `shouldComponentUpdate` because ReactJS does not understand the relationship between binding expressions.

Binding.scala automatically performs what `shouldComponentUpdate` did.

You don't need `shouldComponentUpdate`.

**Pull request merged**
