### PR TITLE
Type-check README example with tut

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**
This PR fixes two typos in the README, and setups [tpolecat/tut](https://github.com/tpolecat/tut) to ensure correctness of these examples in the future.  

Due to some obscure tut/REPL/macro interaction, Scala expressions inside XML literals cannot spawn across multiple lines. That's the reason behind the refactoring of `for` loops using `tableRow` functions.

### CODE REVIEW

**Comment by olafurpg** [comment]
Big +1 from me. Type checked docs are a huge win for both maintainers and users.

**Comment by Atry** [comment]
Looks nice!
I have only one concern. How can we integrate this tool into our CI pipeline in order to auto-generate `README.md`? Is there any best practice for tut with CI?

Though I merged the "Fix typo" commit for now.

**Comment by OlivierBlanvillain** [comment]
Auto-generation would mean that the CI is able to commit and push to GitHub so that's probably a no go. However the CI could probably check that `git status` is clean after running `sbt tut`?

**Comment by Atry** [comment]
@OlivierBlanvillain Did you notice that 5fd00793020fa72f7daa9f85bd3f832737440b53 and 00fb35627d74e2933dfb6446f6019d0c5a8b3eed are pushed from https://travis-ci.org/ThoughtWorksInc/Binding.scala/builds/159198877 ?

**Comment by OlivierBlanvillain** [comment]
Oh, I guess that's possible then. But I think I would still prefer the
"checking for validity" version that on which commits on itself. Or we
would have to be extra smart to prevent a situation where one changes
`/README.md` by hand, CI detects that `/README.md` and `/docs/README.md`
are inconsistent and pushes a new commit to undo whatever was changes
on `/README.md`...

**Comment by Atry** [comment]
I guess we could remove most examples from `README.md`, and provide another set of tutorials instead. The source files of tutorials is in the `9.0.x` branch, and the destination may be wiki.

**Comment by OlivierBlanvillain** [comment]
I did setup something like that for other projects (https://github.com/typelevel/cats/pull/1144 for example), happy to give a hand here if you decide to go that path :)

**Comment by nafg** [comment]
I guess you would use https://github.com/ThoughtWorksInc/example.scala instead ;)

**Comment by Atry** [comment]
Binding.scala is now configured to use [sbt-example](https://github.com/ThoughtWorksInc/sbt-example) to generate tests from Scaladoc.

For example: https://www.javadoc.io/static/com.thoughtworks.binding/binding_2.13/12.1.0+15-e71ae5ee/com/thoughtworks/binding/Binding$$Rx$.html#concat[A](observables:IterableOnce[com.thoughtworks.binding.Binding.Rx.Observable[A]]):com.thoughtworks.binding.Binding.Rx.Observable[A]

**Pull request closed without merging**
